/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aa7a32da-1ac0-4b62-a9df-ce594cb44840",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Euwj3RCrD",
    "aws_user_pools_web_client_id": "28kb1ik94fq8s3logu80m2n7e6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "4e8b1f14ddeb46c0bb14e15656e2b8ec",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
